### PR TITLE
stop reconciling workspace when PVC cleanup job fails 

### LINKED ISSUE #845: DWO continues to reconcile workspace when common PVC cleanup job fails
### Description
When the common PVC cleanup job occurs, if the initial cleanup pod fails, up to 3 more cleanup pods will be created.
If all 4 cleanup pods fail, DWO will continuously log an error regarding being unable to clean up the workspace storage.

Restarting DWO does not fix the issue - it seems the only way to fix this issue is to uninstall and reinstall DWO on the cluster. 

### How To Reproduce

Steps to reproduce the behaviour:
1. Modify the common PVC cleanup job spec (in `pkg/provision/storage/cleanup.go`) so that the created pods will fail (change the container args):

```diff
	Args: []string{
		"-c",
- 		fmt.Sprintf(cleanupCommandFmt, path.Join(pvcClaimMountPath, workspaceId)),
+		 "exit 1",
	},
```

2. Start up DWO
3. Create 2 workspaces that use the common PVC storage-class strategy
4. Delete one of the workspaces so that the common PVC cleanup job will be run
5. Wait for all the PVC cleanup job-related pods to fail
6. DWO will now continuously log an error similar to the following:
```
{"level":"error","ts":1653690734.265899,"logger":"controllers.DevWorkspace","msg":"Failed to clean up DevWorkspace storage","Request.Namespace":"devworkspace-controller","Request.Name":"theia-next","devworkspace_id":"workspace542919afbaf744fa","error":"DevWorkspace PVC cleanup job failed: see logs for job \"cleanup-workspace542919afbaf744fa\" for details","stacktrace":"github.com/devfile/devworkspace-operator/controllers/workspace.(*DevWorkspaceReconciler).finalize\n\t/home/aobuchow/git/devworkspace-operator/controllers/workspace/finalize.go:63\ngithub.com/devfile/devworkspace-operator/controllers/workspace.(*DevWorkspaceReconciler).Reconcile\n\t/home/aobuchow/git/devworkspace-operator/controllers/workspace/devworkspace_controller.go:130\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/aobuchow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/aobuchow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/aobuchow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214"}
```

### Expected behaviour
DWO should stop trying to reconcile the workspace after a certain number of PVC cleanup job failures (or perhaps after the first failure?). The workspace should be marked as failed, and the above-mentioned error should stop being logged.

### PR DESCRIPTION
**Pull request by AObuchow**
### What does this PR do?
Currently, in the reconcile loop, there is a bug with marking a workspace as having an error after the common PVC cleanup job fails.

From my understanding, after detecting that the cleanup job has failed and returning a `ProvisionError` from `storageProvisioner.CleanupWorkspaceStorage()`, the workspace's status phase is set to `Error`. However, the reconcile function checks for deleted workspaces before checking for workspaces with errors/failures. The existing logic in the `finalize` function (which is called when reconciling deleted workspaces) then overwrites the workspace's status phase (setting it to `Terminating`) and eventually runs `storageProvisioner.CleanupWorkspaceStorage()` again, leading to an endless loop.

My current fix simply modifies the `finalize` function to check if the workspace's status phase is set to `Error`, and if so, it does not overwrite the workspace's status phase and returns early.

### What issues does this PR fix or reference?
Fix #845 

### Is it tested? How?
1. Start up DWO
2. Create 2 workspaces that use the common PVC storage-class strategy
3. Delete one of the workspaces so that the common PVC cleanup job will be run, eg. `kubectl delete dw theia-next -n $NAMESPACE`
4. Wait for all the PVC cleanup job-related pods to fail
5. DWO will now log an error similar to the following, **only once**:
```
{"level":"error","ts":1654116778.779755,"logger":"controllers.DevWorkspace","msg":"Failed to clean up DevWorkspace storage","Request.Namespace":"devworkspace-controller","Request.Name":"theia-next","devworkspace_id":"workspace10db2004baac400d","error":"DevWorkspace PVC cleanup job failed: see logs for job \"cleanup-workspace10db2004baac400d\" for details","stacktrace":"github.com/devfile/devworkspace-operator/controllers/workspace.(*DevWorkspaceReconciler).finalize\n\t/home/aobuchow/git/devworkspace-operator/controllers/workspace/finalize.go:64\ngithub.com/devfile/devworkspace-operator/controllers/workspace.(*DevWorkspaceReconciler).Reconcile\n\t/home/aobuchow/git/devworkspace-operator/controllers/workspace/devworkspace_controller.go:130\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/aobuchow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/aobuchow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/aobuchow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214"}
```
6. Ensure that the workspace which was deleted is set to the `Error` phase by doing `kubectl get devworkspace -n $NAMESPACE`:
```
NAME          DEVWORKSPACE ID             PHASE     INFO
theia-next    workspace10db2004baac400d   Error     DevWorkspace PVC cleanup job failed: see logs for job "cleanup-workspace10db2004baac400d" for details
theia-next2   workspace9e7aa15f7aa44c92   Running   https://workspace9e7aa15f7aa44c92-theia-3100.192.168.39.100.nip.io/

```

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspace-operator-e2e, v8-che-happy-path` to trigger)
    - [ ] `v8-devworkspace-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-che-happy-path`: Happy path for verification integration with Che

### CODE REVIEW

File: controllers/workspace/finalize.go [hunk 1]
```diff
@@ -50,19 +50,21 @@ func (r *DevWorkspaceReconciler) workspaceNeedsFinalize(workspace *dw.DevWorkspa
 }
 
 func (r *DevWorkspaceReconciler) finalize(ctx context.Context, log logr.Logger, workspace *dw.DevWorkspace) (reconcile.Result, error) {
-	workspace.Status.Message = "Cleaning up resources for deletion"
-	workspace.Status.Phase = devworkspacePhaseTerminating
-	err := r.Client.Status().Update(ctx, workspace)
-	if err != nil && !k8sErrors.IsConflict(err) {
-		return reconcile.Result{}, err
-	}
+	if workspace.Status.Phase != dw.DevWorkspaceStatusError {
```
Comment (AObuchow) [inline controllers/workspace/finalize.go:53]: There are potentially other places where the workspace status phase may be set to `Error` that do not concern the common PVC cleanup job. 

For example, `finalizeServiceAccount()` may set the workspace status phase to `Error`. Furthermore, it is possible that in the future, other unrelated conditions may set the workspace's status phase to `Error`. 

Thus, it might be best to also check the workspaces condition message for `"Failed to clean up DevWorkspace storage"` in the finalize function (unless this bug also occurs with `finalizeServiceAccount()`, which may be likely? :thinking: )

File: pkg/provision/storage/cleanup.go [hunk 2]
```diff
@@ -146,7 +145,8 @@ func getSpecCommonPVCCleanupJob(workspace *dw.DevWorkspace, clusterAPI sync.Clus
 							Command: []string{"/bin/sh"},
 							Args: []string{
 								"-c",
-								fmt.Sprintf(cleanupCommandFmt, path.Join(pvcClaimMountPath, workspaceId)),
+								"exit 1",
```
Comment (AObuchow) [inline pkg/provision/storage/cleanup.go:148]: This commit/change needs to be removed before the PR can be merged. It's only here to facilitate testing.

**Review by amisevsk — APPROVED** [review]
LGTM.

This PR is pretty far behind `main` right now, and does not include the PVC cleanup changes -- I rebased on main while testing to verify how this works with "cleanup PVC on deletion".

Also, don't forget to remove the temporary patch before merging :)

**Comment by AObuchow** [comment]
> I've tested the PR with the provided instructions, and it is working +1 } I see that:
> 
> ```
> {"level":"error","ts":1654116778.779755,"logger":"controllers.DevWorkspace","msg":"Failed to clean up DevWorkspace storage","Request.Namespace":"devworkspace-controller","Request.Name":"theia-next","devworkspace_id":"workspace10db2004baac400d","error":"DevWorkspace PVC cleanup job failed: see logs for job \"cleanup-workspace10db2004baac400d\" for details","stacktrace":"github.com/devfile/devworkspace-operator/controllers/workspace.(*DevWorkspaceReconciler).finalize\n\t/home/aobuchow/git/devworkspace-operator/controllers/workspace/finalize.go:64\ngithub.com/devfile/devworkspace-operator/controllers/workspace.(*DevWorkspaceReconciler).Reconcile\n\t/home/aobuchow/git/devworkspace-operator/controllers/workspace/devworkspace_controller.go:130\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/aobuchow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/aobuchow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/aobuchow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214"}
> ```
> 
> is being printed quite often, but that is expected since new cleanup pods will start and will fail continuously for our test case, is that right?

Thanks for testing @dkwon17 :)
That error is supposed to be logged, but it should stop being logged after a while - are you seeing it continuously being logged infinitely ? Because if so, the original bug is still occuring.

**Review by ibuziuk — APPROVED** [review]
LGTM, please do not forget to replace exit 1 before merging

**Comment by dkwon17** [comment]
@AObuchow , sorry, I meant to write my comment: https://github.com/devfile/devworkspace-operator/pull/851#issuecomment-1145196196 on your other PR: https://github.com/devfile/devworkspace-operator/pull/846

I just tested this PR and it is working for me 👍

**Comment by AObuchow** [comment]
> @AObuchow , sorry, I meant to write my comment: [#851 (comment)](https://github.com/devfile/devworkspace-operator/pull/851#issuecomment-1145196196) on your other PR: #846
> 
> I just tested this PR and it is working for me , as I only see the
> 
> ```
> Failed to clean up DevWorkspace storage
> ```
> 
> log only once +1

Awesome, thanks for confirmation @dkwon17 :)
